# Imports:

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Hyperparameter:

In [2]:
Jn_name = 'Realized Efficiency'
Jn_name_lowercase = 'realized_efficiency'

In [3]:
make_greyscale = True

In [4]:
if make_greyscale:
    high_contrast_greys = ['#000000', '#808080', '#C0C0C0']
    sns.set_palette(high_contrast_greys)
    savefile_suffix = '_greyscale'
else:
    sns.set_palette('deep')
    savefile_suffix = ''

# Plot Densities when Scheme is Biased in Y:

In [ ]:
fitted_FI_and_corr = pd.read_pickle('sample_by_y_bias.pkl')
df_y_bias = fitted_FI_and_corr

In [6]:
fitted_FI_and_corr.describe()

              srs_fi      biased_fi       srs_corr    biased_corr
count  100000.000000  100000.000000  100000.000000  100000.000000
mean      858.641428     843.940512      -0.000003      -0.003821
std        23.947606      27.302935       0.003165       0.003092
min       750.120000     735.557441      -0.014226      -0.016726
25%       842.452750     825.411701      -0.002143      -0.005908
50%       858.602500     843.833100       0.000002      -0.003823
75%       874.838000     862.445649       0.002141      -0.001739
max       982.528000     994.464286       0.014403       0.008751

# Plot Densities when Scheme is Biased in X:

In [ ]:
fitted_FI_and_corr = pd.read_pickle('sample_by_x_bias.pkl')
df_x_bias = fitted_FI_and_corr

In [11]:
fitted_FI_and_corr.describe()

              srs_fi      biased_fi       srs_corr    biased_corr
count  100000.000000  100000.000000  100000.000000  100000.000000
mean      858.641428    1446.768983      -0.000003      -0.000102
std        23.947606      24.904229       0.003165       0.004106
min       750.120000    1342.132692      -0.014226      -0.017120
25%       842.452750    1429.969134      -0.002143      -0.002863
50%       858.602500    1446.743278       0.000002      -0.000093
75%       874.838000    1463.503612       0.002141       0.002667
max       982.528000    1552.019194       0.014403       0.017901

In [12]:
fitted_FI_and_corr.describe()

              srs_fi      biased_fi       srs_corr    biased_corr
count  100000.000000  100000.000000  100000.000000  100000.000000
mean      858.641428    1446.768983      -0.000003      -0.000102
std        23.947606      24.904229       0.003165       0.004106
min       750.120000    1342.132692      -0.014226      -0.017120
25%       842.452750    1429.969134      -0.002143      -0.002863
50%       858.602500    1446.743278       0.000002      -0.000093
75%       874.838000    1463.503612       0.002141       0.002667
max       982.528000    1552.019194       0.014403       0.017901

### Joint:

In [15]:
fitted_FI_and_corr.corr()

               srs_fi  biased_fi  srs_corr  biased_corr
srs_fi       1.000000   0.555726  0.001127     0.003419
biased_fi    0.555726   1.000000 -0.003619    -0.001995
srs_corr     0.001127  -0.003619  1.000000     0.943055
biased_corr  0.003419  -0.001995  0.943055     1.000000

# Plot Densities when Scheme is Biased in Abs Y:

In [ ]:
fitted_FI_and_corr = pd.read_pickle('sample_by_abs_y_bias.pkl')
df_abs_y_bias = fitted_FI_and_corr

In [18]:
fitted_FI_and_corr.describe()

              srs_fi      biased_fi       srs_corr    biased_corr
count  100000.000000  100000.000000  100000.000000  100000.000000
mean      858.641428    1069.482471      -0.000003       0.038741
std        23.947606      35.691209       0.003165       0.003115
min       750.120000     904.186296      -0.014226       0.025078
25%       842.452750    1045.245314      -0.002143       0.036656
50%       858.602500    1069.359590       0.000002       0.038755
75%       874.838000    1093.588246       0.002141       0.040846
max       982.528000    1232.791322       0.014403       0.052924

In [19]:
fitted_FI_and_corr.corr()

               srs_fi  biased_fi  srs_corr  biased_corr
srs_fi       1.000000   0.725042  0.001127     0.202122
biased_fi    0.725042   1.000000  0.139577     0.203984
srs_corr     0.001127   0.139577  1.000000     0.769759
biased_corr  0.202122   0.203984  0.769759     1.000000

# Aggregated Density Plots (2 x 3): Realized Efficiency & Data Defect Correlation by Sampling Scheme

In [ ]:
schemes = [
    ("Biased in Y", df_y_bias),
    ("Biased in X", df_x_bias),
    ("Biased in Abs Y", df_abs_y_bias),
]
label_map = {
    'srs_corr': 'Unbiased', 'biased_corr': 'Biased',
    'srs_fi': 'Unbiased', 'biased_fi': 'Biased',
}

fig, axes = plt.subplots(2, 3, constrained_layout=True, figsize=(18, 8), sharey='row')
legend_handles, legend_labels = None, None

for col, (title, df) in enumerate(schemes):
    ax = axes[0, col]
    sns.kdeplot(df[['srs_corr', 'biased_corr']], fill=True, ax=ax)
    handles, labels = ax.get_legend_handles_labels()
    if legend_handles is None:
        legend_handles, legend_labels = handles, [label_map[l] for l in labels]
    ax.get_legend().remove()
    ax.set_title(title)
    ax.set_xlabel('Data Defect Correlation')
    ax.set_ylabel('Density' if col == 0 else '')

    ax = axes[1, col]
    sns.kdeplot(df[['srs_fi', 'biased_fi']], fill=True, ax=ax)
    ax.get_legend().remove()
    ax.set_xlabel(Jn_name)
    ax.set_ylabel('Density' if col == 0 else '')

fig.legend(legend_handles, legend_labels, loc="upper center", bbox_to_anchor=(0.5, 1.06), ncol=2)
plt.savefig(f'aggregated_densities_2x3{savefile_suffix}.png', bbox_inches='tight')

# Aggregated Joint Density Plots (1 x 4): Ideal Sample vs Biased Samples

In [ ]:
fig, axes = plt.subplots(1, 4, constrained_layout=True, figsize=(20, 5))

ax = axes[0]
sns.kdeplot(
    data=df_y_bias,
    x="srs_fi",
    y="srs_corr",
    fill=True,
    bw_adjust=1.8,
    levels=5,
    ax=ax,
)
ax.set_xlabel("Ideal Sample")
ax.set_ylabel("")

biased_schemes = [
    ("Biased in Y", df_y_bias),
    ("Biased in X", df_x_bias),
    ("Biased in Abs Y", df_abs_y_bias),
]

for i, (title, df) in enumerate(biased_schemes, start=1):
    ax = axes[i]
    sns.kdeplot(
        data=df,
        x="biased_fi",
        y="biased_corr",
        fill=True,
        bw_adjust=1.8,
        levels=5,
        ax=ax,
    )
    ax.set_xlabel(title)
    ax.set_ylabel("")

fig.supylabel("Data Defect Correlation")
fig.supxlabel(f"{Jn_name} (Across Sampling Mechanisms)")
plt.savefig(f"joint_density_1x4{savefile_suffix}.png", bbox_inches="tight")